/// <reference types="react-scripts" />

/**
 * TypeScript declaration file for Create React App.
 * This file is auto-generated by CRA and provides type definitions
 * for importing non-code assets like images, CSS modules, etc.
 * 
 * DO NOT MODIFY this file directly - it's managed by react-scripts.
 */
